# Generated by Django 5.2 on 2025-04-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookBearApi', '0002_author_genre_publisher_user_followed_authors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='authors'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='publishers'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
