# Generated by Django 5.2 on 2025-04-11 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookBearApi', '0003_author_avatar_book_cover_publisher_logo_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reviewed_books',
        ),
        migrations.AlterField(
            model_name='userbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='BookBearApi.book'),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
